/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContectRouteImport } from './routes/contect'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/App/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductPidRouteImport } from './routes/product.$pid'

const ProductsLazyRouteImport = createFileRoute('/products')()

const ProductsLazyRoute = ProductsLazyRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContectRoute = ContectRouteImport.update({
  id: '/contect',
  path: '/contect',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/App',
  path: '/App',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPidRoute = ProductPidRouteImport.update({
  id: '/product/$pid',
  path: '/product/$pid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/App': typeof AppRouteRoute
  '/about': typeof AboutRoute
  '/contect': typeof ContectRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/products': typeof ProductsLazyRoute
  '/product/$pid': typeof ProductPidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/App': typeof AppRouteRoute
  '/about': typeof AboutRoute
  '/contect': typeof ContectRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/products': typeof ProductsLazyRoute
  '/product/$pid': typeof ProductPidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/App': typeof AppRouteRoute
  '/about': typeof AboutRoute
  '/contect': typeof ContectRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/products': typeof ProductsLazyRoute
  '/product/$pid': typeof ProductPidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/App'
    | '/about'
    | '/contect'
    | '/pricing'
    | '/projects'
    | '/products'
    | '/product/$pid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/App'
    | '/about'
    | '/contect'
    | '/pricing'
    | '/projects'
    | '/products'
    | '/product/$pid'
  id:
    | '__root__'
    | '/'
    | '/App'
    | '/about'
    | '/contect'
    | '/pricing'
    | '/projects'
    | '/products'
    | '/product/$pid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRoute
  AboutRoute: typeof AboutRoute
  ContectRoute: typeof ContectRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRoute
  ProductsLazyRoute: typeof ProductsLazyRoute
  ProductPidRoute: typeof ProductPidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contect': {
      id: '/contect'
      path: '/contect'
      fullPath: '/contect'
      preLoaderRoute: typeof ContectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/App': {
      id: '/App'
      path: '/App'
      fullPath: '/App'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$pid': {
      id: '/product/$pid'
      path: '/product/$pid'
      fullPath: '/product/$pid'
      preLoaderRoute: typeof ProductPidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRoute,
  AboutRoute: AboutRoute,
  ContectRoute: ContectRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRoute,
  ProductsLazyRoute: ProductsLazyRoute,
  ProductPidRoute: ProductPidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
